parameters:
  #experiment
  num_runs: 5
  seed: 0
  # optimizer
  optimizer: SGD
  epoch: 1
  batch: 10
  test_batch: 128
  # validation
  val_size: 0.0
  num_val: -1
  num_runs_val: 1
  # data general
  fix_order: False
  plot_sample: False