parameters:
  #experiment
  num_runs: 10
  seed: 0
  # optimizer
  optimizer: SGD
  epoch: 70
  batch: 128
  test_batch: 128
  # validation
  val_size: 0.0
  num_val: 2
  num_runs_val: 1
  # data general
  fix_order: False
  plot_sample: False
  online: False